# Generated by Django 5.2.7 on 2025-10-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
